# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'npm install'

- script: |
    npm run typecheck
  displayName: 'Running typechecker'

- script: |
    npm run lint
  displayName: 'Running linter'

- script: |
    npm run test
  displayName: 'Running unit tests'

- script: |
    npm run ci
  displayName: 'Building package'
