import { History, Location } from "verlauf";
import React from "react";
import { MatchResult } from "./matchPath";

/** Props provided by all alnilam components to their children. */
export interface RoutingProps {
	/** History instance that used by the ```Router``` */
	history: History;
	/** Current location as reported by ```history``` */
	location: Location;
	/** Match generated by the closest parent ```Route``` or ```Match``` component */
	match?: MatchResult | null;
	/** The the location before last navigation. Initially undefined. */
	previousLocation?: Location;
	staticContext: any; // TODO
}

export type RouterContextType = RoutingProps;

export const RouterContext = React.createContext<RouterContextType | null>(null);
RouterContext.displayName = "RouterContext";
